name: Build Docs

on:
  push:
    branches:
      - main
 
permissions:
  contents: write
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
 
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.9'
 
      - name: install utilities
        run: pip install -r requirements-mkdocs.txt
      
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force