name: Pre-Commit checks

on:
  push:
    branches:
      - main
  pull_request: # Trigger on all by default


jobs:
  pre-commit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install 'pydantic[email]==2.9.2' pre-commit==4.0.1 pydantic_core==2.23.4

      - name:
        run: | 
          pre-commit run --all-files

